import type { Metadata } from "next";
import "./globals.css";
import FontplusLoader from "./components/fontplusLoader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <FontplusLoader />
      </head>
      <body>{children}</body>
    </html>
  );
}
