import type { Metadata } from "next";
import "./globals.css";
import FontplusLoader from "./components/fontplusLoader";
import Scroll from "./components/scroll";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <FontplusLoader />
      </head>
      <body>
        <Scroll>{children}</Scroll>
      </body>
    </html>
  );
}
